format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
import_granularity = "Crate"
reorder_impl_items = true
wrap_comments = true
use_field_init_shorthand = true
newline_style = "Unix"